### ISSUE TITLE
Где Travis CI & CodeCov?

### ISSUE THREAD

**Issue by coursar** [ArthurGaneev/BonusService#2]

**Comment by ArthurGaneev** [comment]
Travis CI & CodeCov добавил.

**Comment by ArthurGaneev** [comment]
Но почему-то не отображается  число процентов покрытия в CodeCov ...

**Comment by ArthurGaneev** [comment]
Все настроил, сейчас отображается!

**Comment by ArthurGaneev** [comment]
Зарываю Issue
