### ISSUE TITLE
Не нужно делать цепочку, если используете return

### ISSUE THREAD

**Issue by coursar** [ArthurGaneev/BonusService#3]
https://github.com/ArthurGaneev/BonusService/blob/be2407a639b030c5bbc323f17e1dcfefa2cb6616/src/main/java/ru/itpark/BonusService.java#L21-L27

```java
if (...) {
    return ...;
}

if (...) {
    return ...;
}
```

**Comment by ArthurGaneev** [comment]
Исправил.Убрал else if.

**Comment by ArthurGaneev** [comment]
Done
